sudo: false
language: node_js
node_js: 6
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
- npm run doc # Ensures ESDoc generation doesn't fail
after_success:
- cat coverage/lcov.info | ./node_modules/.bin/codecov
- cat coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: amercier/npm-package-skeleton # Prevents publishing on PRs
cache:
  directories:
  - $HOME/.nvm
